# Generated by Django 5.0.7 on 2024-08-04 20:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("modules", "0002_alter_trainingmodule_created_at"),
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Institution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "allowed_modules",
                    models.ManyToManyField(
                        related_name="allowed_institutions", to="modules.trainingmodule"
                    ),
                ),
                (
                    "users",
                    models.ManyToManyField(
                        related_name="institutions", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
    ]
