# Generated by Django 5.0.7 on 2024-08-07 18:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("modules", "0002_alter_trainingmodule_created_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ConceptualFoundation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ForumParticipation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.TextField()),
                ("response", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Lecture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="SkillAndLearning",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="SpecificObjective",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name="trainingmodule",
            name="general_objective",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="trainingmodule",
            name="color",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="trainingmodule",
            name="conceptual_foundations",
            field=models.ManyToManyField(blank=True, to="modules.conceptualfoundation"),
        ),
        migrations.AddField(
            model_name="conceptualfoundation",
            name="forum_participation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="modules.forumparticipation",
            ),
        ),
        migrations.AddField(
            model_name="conceptualfoundation",
            name="lecture",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="modules.lecture"
            ),
        ),
        migrations.AddField(
            model_name="trainingmodule",
            name="skills_and_learnings",
            field=models.ManyToManyField(blank=True, to="modules.skillandlearning"),
        ),
        migrations.AddField(
            model_name="trainingmodule",
            name="specific_objectives",
            field=models.ManyToManyField(blank=True, to="modules.specificobjective"),
        ),
        migrations.CreateModel(
            name="VideoUpload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField()),
                ("video_file", models.FileField(upload_to="videos/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="conceptualfoundation",
            name="video_upload",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="modules.videoupload"
            ),
        ),
    ]
