# Generated by Django 5.0.7 on 2024-08-07 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("modules", "0003_conceptualfoundation_forumparticipation_lecture_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trainingmodule",
            name="color",
            field=models.CharField(max_length=7),
        ),
    ]
