# Generated by Django 5.0.7 on 2024-08-07 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("modules", "0004_alter_trainingmodule_color"),
    ]

    operations = [
        migrations.RenameField(
            model_name="lecture",
            old_name="description",
            new_name="content",
        ),
        migrations.RemoveField(
            model_name="videoupload",
            name="author",
        ),
        migrations.AlterField(
            model_name="conceptualfoundation",
            name="forum_participation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="modules.forumparticipation",
            ),
        ),
        migrations.AlterField(
            model_name="conceptualfoundation",
            name="lecture",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="modules.lecture",
            ),
        ),
        migrations.AlterField(
            model_name="conceptualfoundation",
            name="video_upload",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="modules.videoupload",
            ),
        ),
        migrations.AlterField(
            model_name="forumparticipation",
            name="response",
            field=models.TextField(blank=True, null=True),
        ),
    ]
