# Generated by Django 5.0.7 on 2024-08-07 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("modules", "0005_rename_description_lecture_content_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trainingmodule",
            name="author",
        ),
    ]
