# Generated by Django 5.0.7 on 2024-08-07 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("modules", "0006_remove_trainingmodule_author"),
    ]

    operations = [
        migrations.CreateModel(
            name="Evidence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField()),
                (
                    "upload",
                    models.FileField(blank=True, null=True, upload_to="evidence/"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField()),
                ("video_link", models.URLField(blank=True, max_length=300, null=True)),
                (
                    "video_file",
                    models.FileField(blank=True, null=True, upload_to="videos/"),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="conceptualfoundation",
            name="video_upload",
        ),
        migrations.AddField(
            model_name="lecture",
            name="link",
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name="lecture",
            name="content",
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name="CoCreate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("format_text", models.TextField()),
                ("letter", models.TextField(blank=True, null=True)),
                (
                    "forum_participation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="modules.forumparticipation",
                    ),
                ),
                (
                    "lecture",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="modules.lecture",
                    ),
                ),
                (
                    "evidence",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="modules.evidence",
                    ),
                ),
                (
                    "video",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="modules.video",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="trainingmodule",
            name="co_create",
            field=models.ManyToManyField(blank=True, to="modules.cocreate"),
        ),
        migrations.CreateModel(
            name="Engage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "lecture",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="modules.lecture",
                    ),
                ),
                (
                    "video",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="modules.video",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="trainingmodule",
            name="engage",
            field=models.ManyToManyField(blank=True, to="modules.engage"),
        ),
        migrations.AddField(
            model_name="conceptualfoundation",
            name="video",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="modules.video",
            ),
        ),
        migrations.DeleteModel(
            name="VideoUpload",
        ),
    ]
