# Generated by Django 5.0.7 on 2024-08-07 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("modules", "0007_evidence_video_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChoiceQuestionary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("choice_text", models.CharField(max_length=500)),
                ("is_correct", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="OpenQuestionary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.TextField()),
                ("response", models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name="conceptualfoundation",
            name="forum_participation",
        ),
        migrations.RemoveField(
            model_name="conceptualfoundation",
            name="lecture",
        ),
        migrations.RemoveField(
            model_name="conceptualfoundation",
            name="video",
        ),
        migrations.RemoveField(
            model_name="trainingmodule",
            name="conceptual_foundations",
        ),
        migrations.RemoveField(
            model_name="engage",
            name="lecture",
        ),
        migrations.RemoveField(
            model_name="engage",
            name="video",
        ),
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("format_text", models.TextField()),
                ("drafting", models.TextField(blank=True, null=True)),
                (
                    "evidence",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="modules.evidence",
                    ),
                ),
                (
                    "forum_participation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="modules.forumparticipation",
                    ),
                ),
                (
                    "lecture",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="modules.lecture",
                    ),
                ),
                (
                    "video",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="modules.video",
                    ),
                ),
                (
                    "open_questionary",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="modules.openquestionary",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="trainingmodule",
            name="foundations",
            field=models.ManyToManyField(
                blank=True, related_name="foundation_modules", to="modules.activity"
            ),
        ),
        migrations.AddField(
            model_name="trainingmodule",
            name="reflection",
            field=models.ManyToManyField(
                blank=True, related_name="reflection_modules", to="modules.activity"
            ),
        ),
        migrations.AlterField(
            model_name="trainingmodule",
            name="co_create",
            field=models.ManyToManyField(
                blank=True, related_name="co_create_modules", to="modules.activity"
            ),
        ),
        migrations.AlterField(
            model_name="trainingmodule",
            name="engage",
            field=models.ManyToManyField(
                blank=True, related_name="engage_modules", to="modules.activity"
            ),
        ),
        migrations.CreateModel(
            name="SelectionMultipleQuestionary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_text", models.CharField(max_length=500)),
                ("choices", models.ManyToManyField(to="modules.choicequestionary")),
            ],
        ),
        migrations.AddField(
            model_name="activity",
            name="selection_multiple_questionary",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="modules.selectionmultiplequestionary",
            ),
        ),
        migrations.DeleteModel(
            name="CoCreate",
        ),
        migrations.DeleteModel(
            name="ConceptualFoundation",
        ),
        migrations.DeleteModel(
            name="Engage",
        ),
    ]
