# Generated by Django 5.0.7 on 2024-08-07 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("modules", "0008_choicequestionary_openquestionary_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="trainingmodule",
            name="module_name",
            field=models.CharField(default="", max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="trainingmodule",
            name="tag_line",
            field=models.CharField(default="", max_length=200),
            preserve_default=False,
        ),
    ]
