# Generated by Django 5.0.7 on 2024-08-07 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("modules", "0009_trainingmodule_module_name_trainingmodule_tag_line"),
    ]

    operations = [
        migrations.CreateModel(
            name="FormatText",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Redaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField()),
                ("text", models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name="activity",
            name="drafting",
        ),
        migrations.AlterField(
            model_name="activity",
            name="format_text",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="modules.formattext",
            ),
        ),
        migrations.AddField(
            model_name="activity",
            name="redaction",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="modules.redaction",
            ),
        ),
    ]
