# Generated by Django 5.0.7 on 2024-08-07 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0010_formattext_redaction_remove_activity_drafting_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redaction',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
