# Generated by Django 5.0.7 on 2024-08-01 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="content_type",
        ),
        migrations.RemoveField(
            model_name="comment",
            name="object_id",
        ),
    ]
