# Generated by Django 5.0.7 on 2024-08-07 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0003_alter_newsarticle_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="newsarticle",
            name="link",
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
    ]
