# Generated by Django 5.0.7 on 2024-08-07 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0004_newsarticle_category_alter_newsarticle_image"),
        ("content", "0004_newsarticle_link"),
    ]

    operations = []
