# Generated by Django 5.0.7 on 2024-08-07 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0005_merge_20240807_2004"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newsarticle",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="news_images/"),
        ),
    ]
