# Generated by Django 5.0.7 on 2024-08-07 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_newsarticle_link_alter_newsarticle_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='image',
            field=models.ImageField(default=None, upload_to='news_images/'),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='link',
            field=models.TextField(default=''),
        ),
    ]
