# Generated by Django 5.0.7 on 2024-08-07 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_rename_link_newsarticle_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsarticle',
            name='Link',
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='LINK',
            field=models.TextField(default=''),
        ),
    ]
